== FlagAI Project Proposal

*Name of project*: FlagAI

*Requested project maturity level*: Sandbox

=== Project description

FlagAI aims to help researchers and developers to freely train and test large-scale models for NLP tasks. 

* Now it supports GLM, Bert, RoBerta, GPT2, T5 models and models from Huggingface Transformers.
* It provides APIs to quickly download and use those pretrained models on a given text, fine-tune them on your own datasets and then share them with the community on our model hub.
* These models can be applied on Text, for tasks like text classification, information extraction, question answering, summarization, text generation, especially in Chinese.
* FlagAI is backed by the three most popular data/model parallel libraries — PyTorch/Deepspeed/Megatron-LM — with a seamless integration between them. Your can paralle your training/testing process with less than ten lines of code.

=== Statement on alignment with LF AI’s mission

Transformer-based large-scale model is a keypath to *build general AI*. It becames the most powerful and famouse technique lately.

Transformer-based model can *understand natrual language, category images and play vedio games as human beings*:

* Provide off-the-shelf tools for researchers/engneers to train/inference large-scale models, e.g., data-/model- parallel training algorithms. 
* Build-in supports for most used model structures, e.g., encoder, decoder and enc-dec structure. User can even download 10-billion parameters model and run it on a single GPU (V100).
* Build-in supports for many popular downstream tasks. User can directly pull the finetuned model and run the model with a few lines of codes.

FlagAI project will also:

* Easy to use: unified and simplied framework to build and train models.



=== Possible collaboration opportunities with current LF AI hosted projects


FlagAI provide full life-circle for large-scale AI model, especially *inference* and *deploy*:

Potential usage of https://github.com/onnx/[ONNX], to deploy the model.

=== License name

https://github.com/RosaeNLG/rosaenlg/blob/master/LICENSE[Apache 2.0]


=== Source control (GitHub, etc.)

* https://github.com/BAAI-WuDao/[BAAI-WuDao organization on Github]
* https://github.com/BAAI-WuDao/Sailing[main repo]


=== GH DCO app

GH DCO app is active.


=== Issue tracker

https://github.com/BAAI-WuDao/Sailing/issues[Github issues for checking issues and feature requests]


=== Collaboration tools (mailing lists, wiki, IRC, Slack, Glitter, etc.)

* https://github.com/BAAI-WuDao/Sailing/issues[Github issues]
* direct communication with the author by email



=== External dependencies including licenses (name and version) of those dependencies

Models remain under their original licence.

.English specific
[options="header"]
|===
| Model  | Licence
| link:https://github.com/THUDM/GLM/[GLM]  | link:https://github.com/THUDM/GLM/blob/main/LICENSE[MIT]
| link:https://github.com/google-research/bert/[BERT] | link:https://github.com/google-research/bert/blob/master/LICENSE[Apache 2.0]
|===

.Chinese specific
[options="header"]
|===
| Model  | Licence
| link:https://github.com/THUDM/GLM/[GLM]  | link:https://github.com/THUDM/GLM/blob/main/LICENSE[MIT]
| link:https://github.com/ymcui/Chinese-BERT-wwm/[RoBERTa-www-ext] | link:https://github.com/ymcui/Chinese-BERT-wwm/blob/master/LICENSE[Apache 2.0]
| link:https://github.com/renmada/t5-pegasus-pytorch/[t5-pegasus-base] | None
| link:https://github.com/Morizeyao/GPT2-Chinese/[GPT2-Chinese] | link:https://github.com/Morizeyao/GPT2-Chinese/blob/old_gpt_2_chinese_before_2021_4_22/LICENSE[MIT] 
|===

=== Initial committers (name, email, organization) and how long have they been working on project

* Zak Liu, liuguang@baai.ac.cn, BAAI, 3+ month 


=== Have the project defined the roles of contributor, committer, maintainer, etc

Yes, see:

* https://github.com/BAAI-WuDao/Sailing/blob/master/GOVERNANCE.md[GOVERNANCE.md]
* https://github.com/BAAI-WuDao/Sailing/blob/master/CONTRIBUTING.md[CONTRIBUTING.md]


=== Total number of contributors to the project including their affiliations

* Zak Liu, liuguang@baai.ac.cn, https://github.com/BAAI-Open/ [BAAI-Open]




=== Does the project have a code of conduct

https://github.com/BAAI-WuDao/Sailing/blob/master/CODE_OF_CONDUCT.md[FlagAI code of conduct], which refers to https://lfprojects.org/policies/code-of-conduct/.


=== Did the project achieve any of the CII best practices badges

Yes: [TODO]

* https://bestpractices.coreinfrastructure.org/fr/projects/4482[main project on bestpractices.coreinfrastructure.org]


=== Do you have any specific infrastructure requests needed as part of hosting the project in the LF AI?

* Github Actions



=== Project website

* Documentation site and project on Github might be sufficient


=== Project governance

Yes: https://github.com/BAAI-WuDao/Sailing/blob/master/GOVERNANCE.md







